[package]
name = "rustlib"
version = "0.1.0"

[dependencies]
rustr = "*"
indexmap = "*"
rtsonlib = { git = "https://github.com/tercen/rtsonlib", tag = "0.1.2" }

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]
