[package]
name = "rustlib"
version = "0.1.0"

[dependencies]
rustr = "*"
rustson = { git = "https://github.com/tercen/rustson", tag = "0.1.0" }

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]
